name: Arch Linux Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

  # Run build manually
  workflow_dispatch:

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ github.repository_owner }}" --password-stdin
      - name: login to ghcr.io
        run: echo "${{ github.token }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin
      - name: build and push the image
        run: |
          IMAGE_ID=${{ github.repository }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo IMAGE_ID=$IMAGE_ID
          docker buildx build --push --tag "ghcr.io/$IMAGE_ID:latest" --platform linux/amd64 .

          docker push "ghcr.io/$IMAGE_ID:latest"
